name: Bug report
description: Report a problem with installer/docs/packaging
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: What happened and what did you expect?
  - type: input
    id: version
    attributes:
      label: Version
      description: Binary and npm version
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
