name: Documentation Check

on:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/docs-check.yml'

jobs:
  check-links:
    name: Check Markdown Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'no'
          config-file: '.github/markdown-link-check.json'
          folder-path: 'docs/'
          max-depth: 3

      - name: Check root README
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          file-path: './README.md'

  check-format:
    name: Check Markdown Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules --config .markdownlint.json
        continue-on-error: true

  check-spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check spelling
        uses: rojopolis/spellcheck-github-actions@0.35.0
        with:
          config_path: .github/spellcheck-config.yml
          task_name: Markdown
