name: npm publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packaging/npm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Bump package.json version to release tag
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          # Strip leading 'v' if present
          PKG_VERSION="${VERSION#v}"
          echo "Setting package.json version to ${PKG_VERSION}"
          npm version "${PKG_VERSION}" --no-git-tag-version
          cat package.json
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
